spring.application.name=oris_spring
server.port=8087

info.app.name=Testing Spring Actuator
info.app.version=1.0.1
info.app.description=I do my homework

management.endpoints.web.exposure.include=*
management.info.env.enabled=true